version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: polios
      POSTGRES_PASSWORD: polios
      POSTGRES_DB: polios
    ports:
      - "5432:5432"
    volumes:
      - polios_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - polios_redis_data:/data

volumes:
  polios_postgres_data:
  polios_redis_data:
